### ISSUE TITLE
Valgrind analysis and memory management

### ISSUE THREAD

**Issue by dtsullivan** [dtsullivan/ACL#18]

**Comment by bchasnov** [comment]
Look at the memory management of the following layers of abstraction (from low to high)
1. BSocp (mex)
2. csocp (c/c++)
3. cprs (c/c++)
4. scvx (c/c++)
5. optgui (Qt)

In particular, where is dynamic allocation being used in BSocp? Can it be replaced with static memory allocation? Performance loss is ok--main reason for this concern to provide guarantees for onboard aerospace applications.

1. BSocp

In `solver_lib.cpp`, here are the following places where `malloc` is used
- solution variables (line 77)
- r_d, r_p (line 131)
- outputs (line 448)
- output framework (1260): `
- package output (1508)

The sizes are pretty much all either `par.n`, `par.neq`, `worksize`,  `sizeof(slvOut_t)` or `Niters`.
