### ISSUE TITLE
Tablet bugs - from beta testing

### ISSUE THREAD

**Issue by mceowen** [dtsullivan/ACL#82]
- a_min should be forbidden from being greater than a_max
- add error messages for expert panel in textbox
- better names for optimization problem params (talk w/ Danylo)
- gui crashes when live-tracked obstacle ellipse is erased
- traj gen glitches out when mobile obstacle is used 
- set initial velocity to current velocity for traj update
- set t_k for waypoints as r_k/v_avg

**Comment by mceowen** [comment]
Remove the following from expert panel:
- dk
- n_recalcs

**Comment by dtsullivan** [comment]
a_min should be forbidden from being greater than a_max, remove dK and n_recalcs - moved to Issue https://github.com/dtsullivan/optgui/issues/84#issue-577205978

set t_k for waypoints as r_k/v_avg - Falls under issue https://github.com/dtsullivan/optgui/issues/81#issue-575900624

set initial velocity to current velocity for traj update - falls under issue https://github.com/dtsullivan/optgui/issues/74#issue-570819417

add error messages for expert panel in textbox - falls under issue https://github.com/dtsullivan/optgui/issues/53#issue-559386934
