### ISSUE TITLE
Multiple trajectories

### ISSUE THREAD

**Issue by dtsullivan** [dtsullivan/ACL#95]

**Comment by bchasnov** [comment]
@dtsullivan I think we have some low-hanging fruit here that we can do. To manage multiple trajectories, we can add logic like so:
```python
operating_point = problem.init() # initialize problem 
ops = [operationg_point]
for ever in forever:
    for op in ops:
        op = problem.step(op)
    if once_in_a_while:
        ops.append(problem.init())
        ops = prune(ops, tol=0.01, max_op=10, sort_by='cost')
```
and constantly plot the multiple solutions in `ops`. The manager would maintain a list of different operating points (approximate local minima), and allow re-initialization once in a while. Use case of this would be:
* if you dragged an obstacle to push the trajectory away, re-initializing will allow the algorithm to rediscover the original `straight-line` trajectory that was more optimal, and plot both.
* if `problem.init()` returned multiple initializations, it might be able to find the different paths through obstacles. e.g. if you used a random waypoint to sample a bunch of initial trajectories and start the iteration from there, you could 'discover' the different local equilibria and select between them
* you could sort the resulting trajectories by different criterion, or arbiturary 'what looks best to me' human interaction.
* this could be quite important for the human interaction portion of the paper...

Then, after this, we can add the multiple final points and selecting between them. It would be as simple as adding the final point as an operating point of the problem.

**Comment by dtsullivan** [comment]
So it seems like this proposed solution is still solving all trajectories in one thread. I was planning on simply spawning a thread for each trajectory. This takes advantage of [user thread](https://www.tutorialspoint.com/user-level-threads-and-kernel-level-threads) functionality and lets the OS manage the execution of calling socp (whether it should be in a loop or actually a different thread) to optimize performance.

**Comment by bchasnov** [comment]
Cool, yeah it would be really nice to replace the inner loop with the
threaded version if that is possible. The key point here is to constantly
reinitialize the problem and prune similar solutions, whether that is just
done sequentially or in a thread
